# -*- coding: utf-8 -*-
"""AlgoritmoSupervisionado.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wedic-h3PiIV631WX-i28AdwV-LtnC-y

# Projeto Interativo: Classificação de Vinhos com Scikit-Learn
"""

# Importar bibliotecas
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.datasets import load_wine
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier

"""## Carregar e explorar o dataset"""

wine = load_wine()
df = pd.DataFrame(wine.data, columns=wine.feature_names)
df['target'] = wine.target
df['class'] = df['target'].apply(lambda x: wine.target_names[x])

df.head()

"""## Distribuição das classes"""

sns.countplot(x='class', data=df)
plt.title('Distribuição das classes de vinho')
plt.show()

df.info()

"""## Visualização das features"""

# Carregar o dataset
wine = load_wine()
df = pd.DataFrame(wine.data, columns=wine.feature_names)

# Gerar matriz de correlação
corr_matrix = df.corr()

# Visualizar com heatmap
plt.figure(figsize=(12,10))
sns.heatmap(corr_matrix, annot=True, cmap='coolwarm', fmt=".2f", linewidths=0.5)
plt.title('🔗 Matriz de Correlação - Dataset Vinho')
plt.show()

"""Interpretação rápida
• Correlação próxima de 1 → forte relação positiva
• Correlação próxima de -1 → forte relação negativa
• Correlação próxima de 0 → pouca ou nenhuma relação

Correlações Fortes Positivas (↑)
Essas variáveis têm alta associação e podem indicar redundância ou relevância conjunta:
- flavanoids e total_phenols → 0.86
→ Flavonoides são um tipo de fenol, então essa correlação é esperada. Ambas são ótimas para distinguir tipos de vinho.
- od280/od315_of_diluted_wines e flavanoids → 0.79
→ Alta absorção óptica está ligada à concentração de flavonoides, o que pode indicar qualidade.
- alcohol e od280/od315_of_diluted_wines → 0.72
→ Vinhos com maior teor alcoólico tendem a ter maior absorção óptica, sugerindo maior concentração de compostos.
- proline e alcohol → 0.71
→ Prolina, um aminoácido, pode estar associada à maturação ou qualidade do vinho.
----------------------------------------------------------------------------
Correlações Fortes Negativas (↓)
Essas variáveis se movem em direções opostas e podem ajudar a contrastar classes:
- flavanoids e nonflavanoid_phenols → −0.43
→ Relação inversa entre tipos de fenóis. Pode indicar equilíbrio químico entre compostos.
- color_intensity e hue → −0.56
→ Vinhos mais intensos em cor tendem a ter tonalidade mais baixa. Útil para distinguir visualmente os tipos.
----------------------------------------------------------------------------
- Variáveis com alta correlação positiva podem ser redundantes → úteis para redução de dimensionalidade com PCA.
- Variáveis com boa separação entre classes (como flavanoids, alcohol, od280/od315) são excelentes para modelos de classificação.
- Correlações negativas ajudam a contrastar padrões entre classes, especialmente em modelos baseados em árvores.

## Pré-processamento
"""

# Carregar o dataset
wine = load_wine()
df = pd.DataFrame(wine.data, columns=wine.feature_names)
df['target'] = wine.target
df['class'] = df['target'].apply(lambda x: wine.target_names[x])

X = df[wine.feature_names]
y = df['target']

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

"""## Treinar e comparar modelos"""

models = {
    'Logistic Regression': LogisticRegression(max_iter=500),
    'Decision Tree': DecisionTreeClassifier(),
    'Random Forest': RandomForestClassifier(),
    'SVM': SVC(),
    'KNN': KNeighborsClassifier()
}

results = []

for name, model in models.items():
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    acc = accuracy_score(y_test, y_pred)
    results.append({'Model': name, 'Accuracy': acc})

"""Visualizar desempenho"""

results_df = pd.DataFrame(results).sort_values(by='Accuracy', ascending=False)

sns.barplot(x='Accuracy', y='Model', data=results_df)
plt.title('Comparação de acurácia entre modelos (dataset vinho)')
plt.xlim(0.8, 1.0)
plt.show()

"""## Relatório de melhor modelo"""

best_model_name = results_df.iloc[0]['Model']
best_model = models[best_model_name]
y_pred = best_model.predict(X_test)

print(f'Melhor modelo: {best_model_name}')
print(classification_report(y_test, y_pred, target_names=wine.target_names))

"""## Análise Final"""

# Respostas às perguntas
print("➡️ Melhor modelo:", best_model_name)
print("➡️ Classes mais difíceis de prever: verifique precisão e recall no classification_report acima.")
print("➡️ O uso de StandardScaler influenciou os resultados: sim, especialmente para SVM, KNN e Logistic Regression.")